dist: xenial
branches:
  except:
  - "/^wip/"
language: java
jdk:
  - openjdk11
cache:
  directories:
  - lib/
install:
  - sudo apt-get update -q -y
  - sudo apt-get install -y realpath python3-yaml ant
  - ./pull-dependencies.sh
script:
  - ant
  - ./scripts/ci.sh

