dist: xenial
branches:
  except:
  - "/^wip/"
language: java
jdk:
  - openjdk8
services:
  - docker
cache:
  directories:
  - lib/
install:
  - sudo apt-get update -q -y
  - sudo apt-get install -y realpath python3-yaml ant
  - ./pull-dependencies.sh
script:
  - ant
  - ./scripts/ci.sh
  - docker build -t almond-tokenizer:$(git describe) docker/ --build-arg ALMOND_TOKENIZER_VERSION=$(git describe)
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} || true
deploy:
  provider: script
  script: docker push almond-tokenizer:$(git describe)
  on:
    tags: true
    repo: stanford-oval/almond-tokenizer

